# Generated by Django 3.1 on 2020-08-22 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c03f470f-e734-48b8-9a67-8ef046e727f3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
