# Generated by Django 3.1 on 2020-08-22 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200822_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aaf07405-3ade-47c9-bf3a-f94a9c6617c2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
