# Generated by Django 3.1 on 2020-08-23 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200822_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_default_company',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2c2f845-b6d1-4969-bf65-0bdd9b62fee4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
