# Generated by Django 3.1 on 2020-08-23 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200823_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ff4dba8-62e3-4162-b4c9-7eb7fcec3c6a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
