# Generated by Django 3.1 on 2020-08-23 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200823_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ed63bb6-22f1-4c9f-9464-e071914290ea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
