# Generated by Django 3.1 on 2020-08-23 11:06

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200823_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=accounts.models.get_default_company, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.company'),
        ),
    ]
